[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/api/v1/countries/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
