# Generated by Django 4.2.29 on 2026-03-17 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                ("max_levels", models.PositiveSmallIntegerField(default=4)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("name_sw", models.CharField(blank=True, max_length=255)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("native_id", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="divisions.country",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="divisions.division",
                    ),
                ),
            ],
            options={
                "ordering": ["country", "level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Era",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_local", models.CharField(blank=True, max_length=200)),
                (
                    "era_type",
                    models.CharField(
                        choices=[
                            ("precolonial", "Pre-colonial"),
                            ("colonial", "Colonial"),
                            ("independence", "Independence"),
                            ("current", "Current"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "colonial_power",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("british", "British"),
                            ("belgian", "Belgian"),
                            ("german", "German"),
                            ("french", "French"),
                            ("italian", "Italian"),
                            ("portuguese", "Portuguese"),
                            ("", "N/A"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started", models.CharField(blank=True, max_length=20)),
                ("ended", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eras",
                        to="divisions.country",
                    ),
                ),
            ],
            options={
                "ordering": ["country", "started"],
                "unique_together": {("country", "name")},
            },
        ),
        migrations.CreateModel(
            name="DivisionName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("language", models.CharField(blank=True, max_length=100)),
                (
                    "name_type",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("indigenous", "Indigenous / Pre-colonial"),
                            ("colonial", "Colonial"),
                            ("colloquial", "Colloquial"),
                            ("historical", "Historical"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
                ("etymology", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_names",
                        to="divisions.division",
                    ),
                ),
                (
                    "era",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_names",
                        to="divisions.era",
                    ),
                ),
            ],
            options={
                "ordering": ["era__started", "name_type"],
                "unique_together": {("division", "era", "language", "name_type")},
            },
        ),
        migrations.CreateModel(
            name="DivisionLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("name_sw", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_levels",
                        to="divisions.country",
                    ),
                ),
            ],
            options={
                "ordering": ["country", "level"],
                "unique_together": {("country", "level")},
            },
        ),
        migrations.AddIndex(
            model_name="division",
            index=models.Index(
                fields=["country", "level"], name="divisions_d_country_5679c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="division",
            index=models.Index(
                fields=["parent"], name="divisions_d_parent__05bfc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="division",
            index=models.Index(fields=["code"], name="divisions_d_code_6cc01b_idx"),
        ),
    ]
