# Generated by Django 4.2.29 on 2026-03-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("divisions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
