# Generated by Django 4.2.29 on 2026-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("divisions", "0002_add_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
